apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: game-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: game-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP