apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-service
  name: game-service
  namespace: game-service
spec:
  selector:
    matchLabels:
      app: game-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/nordeus-sre-challenge/sre-challenge-images/game-service:1.0.2
        imagePullPolicy: IfNotPresent
        name: game-service
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
