apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: game-service
spec:
  type: LoadBalancer
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000